### ISSUE TITLE
Data is null

### ISSUE THREAD

**Issue by SwapanpreetKaur** [adamlenart/decision-tree-vis#24]
Not able to find this data/d3tree_data.json file in  decision tree visualisation in 
dtvis/index.html?? 

Error : data is null

**Comment by adamlenart** [comment]
Yeah, thanks for pointing out, I wasn't actively tracking the json because the (tracked) example notebook could create it but now it is uploaded. Sorry for the missing documentation and the terrible folder structure, when I will have more time, I will get back to working on this project.
